// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE;

/************************************************************/
/**
 * 
 */
class Character {
	/**
	 * 
	 */
	protected String name;
	/**
	 * 
	 */
	protected int attack;
	/**
	 * 
	 */
	protected int health;
	/**
	 * 
	 */
	protected categories category;
	/**
	 * 
	 */
	protected int healthMax;

	/**
	 * 
	 */
	public void heal() {
	}

	/**
	 * 
	 */
	public void takeDamage() {
	}

	/**
	 * 
	 */
	public void attack() {
	}
};
