// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	public Player[] player;
	/**
	 * 
	 */
	public PlayerInterface playerinterface;

	/**
	 * 
	 */
	public void startGame() {
	}
};
