// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE;

/************************************************************/
/**
 * 
 */
public class Human extends Player {
	/**
	 * 
	 */
	private String name;

	/**
	 * 
	 */
	public void attack() {
	}

	/**
	 * 
	 */
	public void selectHeroes() {
	}
};
