// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int damageGiven;
	/**
	 * 
	 */
	private int damageTaken;
	/**
	 * 
	 */
	private Character characters;
	/**
	 * 
	 */
	public Character[] character;
};
