// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE;

/************************************************************/
/**
 * 
 */
public class PlayerInterface {
	/**
	 * 
	 */
	public void beginGame() {
	}

	/**
	 * 
	 */
	public void showStats() {
	}

	/**
	 * 
	 */
	public void attack() {
	}

	/**
	 * 
	 */
	public void pickHeros() {
	}
};
