// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE;

/************************************************************/
/**
 * 
 */
public class SpecialCharacter extends Character {
	/**
	 * 
	 */
	public void specialAttack() {
	}
};
